apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rep
  namespace: temp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-rep-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-cont
          image: nginx
          ports:
            - containerPort: 80

