apiVersion: apps/v1
kind: Deployment
metadata:
  name: promexample
  labels:
    app: promexample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promexample
  template:
    metadata:
      labels:
        app: promexample
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: promexample
          image: arush75/promexample:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: promexample
  labels:
    app: promexample         
spec:
  selector:
    app: promexample
  ports:
    - name: metrics         
      port: 8080
      targetPort: 8080
      nodePort: 31005
  type: NodePort

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: promexample-monitor
  labels:
    release: kind-prometheus   
spec:
  selector:
    matchLabels:
      app: promexample         
  namespaceSelector:
    matchNames:
      - temp                   
  endpoints:
    - port: metrics            
      interval: 10s
