stages:
  - stage1
  - stage3
  - stage2
  - stage4
  - stage5_6
  - stage7
  - stage8

# Stage 1
job_stage1:
  stage: stage1
  script:
    - echo "I am Stage 1"
  tags:
    - edith

# Stage 3 (depends on Stage 1)
job_stage3:
  stage: stage3
  script:
    - echo "I am Stage 3"
  needs: [job_stage1]
  tags:
    - edith

# Stage 2 (depends on Stage 3)
job_stage2:
  stage: stage2
  script:
    - echo "I am Stage 2"
  needs: [job_stage3]
  tags:
    - edith

# Stage 4 (doesn't depend on anything)
job_stage4:
  stage: stage4
  script:
    - echo "I am Stage 4"
  tags:
    - edith

# Stage 5 and Stage 6 (parallel after Stage 2 and 4)
job_stage5:
  stage: stage5_6
  script:
    - echo "I am Stage 5"
  needs: [job_stage2, job_stage4]
  tags:
    - edith

job_stage6:
  stage: stage5_6
  script:
    - echo "I am Stage 6"
  needs: [job_stage2, job_stage4]
  tags:
    - edith

# Stage 7 (depends only on Stage 5)
job_stage7:
  stage: stage7
  script:
    - echo "I am Stage 7 (depends only on Stage 5)"
  needs: [job_stage5]
  tags:
    - edith

# Stage 8 (complex dependencies: Stage 6 OR Stage 7)
job_stage8:
  stage: stage8
  script:
    - echo "I am Stage 8 (can run after Stage 6 or Stage 7)"
  needs: [job_stage6, job_stage7]
  tags:
    - edith

# Optional job (won't fail pipeline)
optional_job:
  stage: stage4
  script:
    - echo "This is an optional job"
    - exit 1
  allow_failure: true
  rules:
    - when: always
  tags:
    - edith

# Artifacts example
job_with_artifact:
  stage: stage3
  script:
    - echo "Hello from Artifact Job" > artifact.txt
    - cat artifact.txt
  artifacts:
    paths:
      - artifact.txt
  needs: [job_stage1]
  tags:
    - edith
