apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: apache
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    args:
      - -c
      - >
        while true; do
          wget -q -O - http://apache-svc.apache.svc.cluster.local > /dev/null;
        done
    resources:
      limits:
        cpu: "300m"
        memory: "128Mi"
      requests:
        cpu: "300m"
        memory: "128Mi"
  restartPolicy: Never
