apiVersion: v1
kind: Namespace
metadata:
  name: apache


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-dep
  namespace: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      name: apache-pod
      labels:
        app: apache
    spec:
      containers:
      - name: apache-cont
        image: httpd:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  namespace: apachekubectl 
spec:
  selector:
    app: apache
  ports:
  - port: 80
    targetPort: 80


---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: apache-vpa
  namespace: apache
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-dep
  updatePolicy:
    updateMode: "Auto"
  # resourcePolicy:
  #   containerPolicies:
  #   - containerName: apache-cont
  #     controlledResources: ["memory"]
  #     minAllowed:
  #       memory: "64Mi"
  #     maxAllowed:
  #       memory: "512Mi"

