{
 "title": "Nginx load dashborad",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network IN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"} - node_filesystem_free_bytes{fstype!~\"tmpfs|overlay\"}) / node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"} * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rquest pers econd",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[1m]))\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}